# Generated by Django 5.1.4 on 2024-12-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отеля')),
                ('description', models.TextField(verbose_name='Описание')),
                ('location', models.CharField(max_length=200, verbose_name='Местоположение')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Рейтинг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/', verbose_name='Изображение отеля')),
            ],
        ),
    ]
