# Generated by Django 5.1.4 on 2024-12-13 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_hotel_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default='', help_text='Формат: +123456789. До 15 цифр.', max_length=15, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона.', regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
