# Generated by Django 5.1.4 on 2024-12-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Одноместная'), ('double', 'Двухместная'), ('suite', 'Люкс')], max_length=10),
        ),
    ]
