# Generated by Django 5.1.4 on 2024-12-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_guests',
            field=models.PositiveIntegerField(default=1, verbose_name='Максимальное количество гостей'),
        ),
    ]
