# Generated by Django 5.1.4 on 2024-12-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_room_max_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Одноместная'), ('double', 'Двухместная'), ('suite', 'Люкс')], max_length=50),
        ),
    ]
